// Generated from prisma/foods-seed.json for local-first startup.
window.EAT_SEED = {
  "version": 1,
  "generated_at": "2026-05-18T23:03:29.832Z",
  "foods": [
    {
      "id": "pasta-pomodoro",
      "name": "Pasta al pomodoro",
      "cat": "Primi piatti",
      "kcal": 148,
      "p": 4.6,
      "c": 27.2,
      "f": 2.4,
      "fb": 1.8,
      "sg": 3.4,
      "sf": 0.5,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "pasta-carbonara",
      "name": "Pasta alla carbonara",
      "cat": "Primi piatti",
      "kcal": 232,
      "p": 11.3,
      "c": 22.8,
      "f": 10.9,
      "fb": 1.2,
      "sg": 1.6,
      "sf": 4.1,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "pasta-pesto",
      "name": "Pasta al pesto",
      "cat": "Primi piatti",
      "kcal": 218,
      "p": 6.4,
      "c": 24.1,
      "f": 10.3,
      "fb": 1.6,
      "sg": 1.2,
      "sf": 1.9,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "riso-bianco",
      "name": "Riso bianco cotto",
      "cat": "Cereali",
      "kcal": 130,
      "p": 2.7,
      "c": 28.2,
      "f": 0.3,
      "fb": 0.4,
      "sg": 0.1,
      "sf": 0.1,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "risotto-funghi",
      "name": "Risotto ai funghi",
      "cat": "Primi piatti",
      "kcal": 168,
      "p": 4.2,
      "c": 27,
      "f": 4.6,
      "fb": 1.4,
      "sg": 0.8,
      "sf": 1.8,
      "unit": "g",
      "serving": 200
    },
    {
      "id": "pollo-petto",
      "name": "Petto di pollo",
      "cat": "Carni",
      "kcal": 165,
      "p": 31,
      "c": 0,
      "f": 3.6,
      "fb": 0,
      "sg": 0,
      "sf": 1,
      "unit": "g",
      "serving": 120
    },
    {
      "id": "salmone",
      "name": "Salmone al forno",
      "cat": "Pesci",
      "kcal": 208,
      "p": 22.1,
      "c": 0,
      "f": 13.4,
      "fb": 0,
      "sg": 0,
      "sf": 3.1,
      "unit": "g",
      "serving": 130
    },
    {
      "id": "tonno-naturale",
      "name": "Tonno al naturale",
      "cat": "Pesci",
      "kcal": 116,
      "p": 25.5,
      "c": 0,
      "f": 1,
      "fb": 0,
      "sg": 0,
      "sf": 0.3,
      "unit": "g",
      "serving": 80
    },
    {
      "id": "uovo",
      "name": "Uovo intero",
      "cat": "Uova & latticini",
      "kcal": 155,
      "p": 13,
      "c": 1.1,
      "f": 11,
      "fb": 0,
      "sg": 1.1,
      "sf": 3.3,
      "unit": "pz",
      "serving": 1,
      "per_unit_g": 55
    },
    {
      "id": "manzo-tagliata",
      "name": "Tagliata di manzo",
      "cat": "Carni",
      "kcal": 217,
      "p": 26,
      "c": 0,
      "f": 12.1,
      "fb": 0,
      "sg": 0,
      "sf": 4.8,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "yogurt-greco",
      "name": "Yogurt greco 2%",
      "cat": "Uova & latticini",
      "kcal": 73,
      "p": 9.1,
      "c": 3.6,
      "f": 1.9,
      "fb": 0,
      "sg": 3.6,
      "sf": 1.3,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "mozzarella",
      "name": "Mozzarella fior di latte",
      "cat": "Uova & latticini",
      "kcal": 253,
      "p": 18.7,
      "c": 0.6,
      "f": 19.5,
      "fb": 0,
      "sg": 0.6,
      "sf": 12.4,
      "unit": "g",
      "serving": 80
    },
    {
      "id": "ricotta",
      "name": "Ricotta vaccina",
      "cat": "Uova & latticini",
      "kcal": 146,
      "p": 9.5,
      "c": 3.5,
      "f": 10.9,
      "fb": 0,
      "sg": 3.2,
      "sf": 7,
      "unit": "g",
      "serving": 100
    },
    {
      "id": "latte-parz",
      "name": "Latte parzialmente scremato",
      "cat": "Uova & latticini",
      "kcal": 46,
      "p": 3.3,
      "c": 4.8,
      "f": 1.5,
      "fb": 0,
      "sg": 4.8,
      "sf": 1,
      "unit": "ml",
      "serving": 200
    },
    {
      "id": "parmigiano",
      "name": "Parmigiano Reggiano",
      "cat": "Uova & latticini",
      "kcal": 392,
      "p": 32.4,
      "c": 0,
      "f": 28.4,
      "fb": 0,
      "sg": 0,
      "sf": 19,
      "unit": "g",
      "serving": 15
    },
    {
      "id": "pane-integrale",
      "name": "Pane integrale",
      "cat": "Pane & cereali",
      "kcal": 247,
      "p": 9,
      "c": 41,
      "f": 2.8,
      "fb": 7,
      "sg": 4,
      "sf": 0.6,
      "unit": "g",
      "serving": 50
    },
    {
      "id": "pane-bianco",
      "name": "Pane bianco",
      "cat": "Pane & cereali",
      "kcal": 265,
      "p": 9,
      "c": 49,
      "f": 3.2,
      "fb": 2.7,
      "sg": 5,
      "sf": 0.7,
      "unit": "g",
      "serving": 50
    },
    {
      "id": "fette-biscottate",
      "name": "Fette biscottate",
      "cat": "Pane & cereali",
      "kcal": 408,
      "p": 12.5,
      "c": 79,
      "f": 5.6,
      "fb": 3.5,
      "sg": 6,
      "sf": 0.9,
      "unit": "pz",
      "serving": 2,
      "per_unit_g": 8
    },
    {
      "id": "avena-fiocchi",
      "name": "Fiocchi d’avena",
      "cat": "Pane & cereali",
      "kcal": 389,
      "p": 16.9,
      "c": 66.3,
      "f": 6.9,
      "fb": 10.6,
      "sg": 1,
      "sf": 1.2,
      "unit": "g",
      "serving": 40
    },
    {
      "id": "insalata-mista",
      "name": "Insalata mista",
      "cat": "Verdure",
      "kcal": 18,
      "p": 1.4,
      "c": 2.9,
      "f": 0.2,
      "fb": 1.8,
      "sg": 1.6,
      "sf": 0,
      "unit": "g",
      "serving": 100
    },
    {
      "id": "pomodori",
      "name": "Pomodori freschi",
      "cat": "Verdure",
      "kcal": 19,
      "p": 0.9,
      "c": 3.5,
      "f": 0.2,
      "fb": 1.2,
      "sg": 2.6,
      "sf": 0,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "broccoli",
      "name": "Broccoli al vapore",
      "cat": "Verdure",
      "kcal": 35,
      "p": 2.4,
      "c": 7.2,
      "f": 0.4,
      "fb": 3.3,
      "sg": 1.7,
      "sf": 0,
      "unit": "g",
      "serving": 200
    },
    {
      "id": "patate",
      "name": "Patate al forno",
      "cat": "Verdure",
      "kcal": 110,
      "p": 2.4,
      "c": 25,
      "f": 0.2,
      "fb": 2.5,
      "sg": 1,
      "sf": 0,
      "unit": "g",
      "serving": 200
    },
    {
      "id": "ceci",
      "name": "Ceci lessati",
      "cat": "Legumi",
      "kcal": 164,
      "p": 8.9,
      "c": 27.4,
      "f": 2.6,
      "fb": 7.6,
      "sg": 4.8,
      "sf": 0.3,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "lenticchie",
      "name": "Lenticchie lessate",
      "cat": "Legumi",
      "kcal": 116,
      "p": 9,
      "c": 20.1,
      "f": 0.4,
      "fb": 7.9,
      "sg": 1.8,
      "sf": 0.1,
      "unit": "g",
      "serving": 150
    },
    {
      "id": "mela",
      "name": "Mela",
      "cat": "Frutta",
      "kcal": 52,
      "p": 0.3,
      "c": 13.8,
      "f": 0.2,
      "fb": 2.4,
      "sg": 10.4,
      "sf": 0,
      "unit": "pz",
      "serving": 1,
      "per_unit_g": 180
    },
    {
      "id": "banana",
      "name": "Banana",
      "cat": "Frutta",
      "kcal": 89,
      "p": 1.1,
      "c": 22.8,
      "f": 0.3,
      "fb": 2.6,
      "sg": 12.2,
      "sf": 0.1,
      "unit": "pz",
      "serving": 1,
      "per_unit_g": 120
    },
    {
      "id": "mirtilli",
      "name": "Mirtilli",
      "cat": "Frutta",
      "kcal": 57,
      "p": 0.7,
      "c": 14.5,
      "f": 0.3,
      "fb": 2.4,
      "sg": 9.7,
      "sf": 0,
      "unit": "g",
      "serving": 100
    },
    {
      "id": "arancia",
      "name": "Arancia",
      "cat": "Frutta",
      "kcal": 47,
      "p": 0.9,
      "c": 11.7,
      "f": 0.1,
      "fb": 2.4,
      "sg": 9.4,
      "sf": 0,
      "unit": "pz",
      "serving": 1,
      "per_unit_g": 200
    },
    {
      "id": "caffe-espresso",
      "name": "Caffè espresso",
      "cat": "Bevande",
      "kcal": 2,
      "p": 0.1,
      "c": 0.3,
      "f": 0,
      "fb": 0,
      "sg": 0,
      "sf": 0,
      "unit": "pz",
      "serving": 1,
      "per_unit_g": 30
    },
    {
      "id": "cappuccino",
      "name": "Cappuccino",
      "cat": "Bevande",
      "kcal": 56,
      "p": 3,
      "c": 4.5,
      "f": 2.4,
      "fb": 0,
      "sg": 4.5,
      "sf": 1.5,
      "unit": "ml",
      "serving": 150
    },
    {
      "id": "spremuta",
      "name": "Spremuta d’arancia",
      "cat": "Bevande",
      "kcal": 45,
      "p": 0.7,
      "c": 10.4,
      "f": 0.2,
      "fb": 0.2,
      "sg": 8.4,
      "sf": 0,
      "unit": "ml",
      "serving": 200
    },
    {
      "id": "mandorle",
      "name": "Mandorle",
      "cat": "Frutta secca",
      "kcal": 579,
      "p": 21.2,
      "c": 21.6,
      "f": 49.9,
      "fb": 12.5,
      "sg": 4.4,
      "sf": 3.8,
      "unit": "g",
      "serving": 25
    },
    {
      "id": "noci",
      "name": "Noci",
      "cat": "Frutta secca",
      "kcal": 654,
      "p": 15.2,
      "c": 13.7,
      "f": 65.2,
      "fb": 6.7,
      "sg": 2.6,
      "sf": 6.1,
      "unit": "g",
      "serving": 25
    },
    {
      "id": "cioccolato-fond",
      "name": "Cioccolato fondente 70%",
      "cat": "Dolci",
      "kcal": 598,
      "p": 7.8,
      "c": 45.9,
      "f": 42.6,
      "fb": 10.9,
      "sg": 24,
      "sf": 24.5,
      "unit": "g",
      "serving": 20
    },
    {
      "id": "cornetto",
      "name": "Cornetto vuoto",
      "cat": "Dolci",
      "kcal": 406,
      "p": 8.2,
      "c": 45.8,
      "f": 21,
      "fb": 1.5,
      "sg": 11.3,
      "sf": 13.1,
      "unit": "pz",
      "serving": 1,
      "per_unit_g": 70
    },
    {
      "id": "biscotti-frollini",
      "name": "Biscotti frollini",
      "cat": "Dolci",
      "kcal": 460,
      "p": 6.5,
      "c": 67,
      "f": 18,
      "fb": 2,
      "sg": 22,
      "sf": 9,
      "unit": "g",
      "serving": 30
    },
    {
      "id": "olio-evo",
      "name": "Olio extravergine d’oliva",
      "cat": "Condimenti",
      "kcal": 884,
      "p": 0,
      "c": 0,
      "f": 100,
      "fb": 0,
      "sg": 0,
      "sf": 14,
      "unit": "g",
      "serving": 10
    }
  ],
  "favorites": [
    {
      "id": "fav1",
      "name": "Colazione proteica",
      "items": [
        [
          "yogurt-greco",
          150,
          "g"
        ],
        [
          "mirtilli",
          80,
          "g"
        ],
        [
          "avena-fiocchi",
          40,
          "g"
        ]
      ]
    },
    {
      "id": "fav2",
      "name": "Pranzo veloce ufficio",
      "items": [
        [
          "pasta-pomodoro",
          150,
          "g"
        ],
        [
          "insalata-mista",
          80,
          "g"
        ],
        [
          "mela",
          1,
          "pz"
        ]
      ]
    },
    {
      "id": "fav3",
      "name": "Cena post-allenamento",
      "items": [
        [
          "pollo-petto",
          150,
          "g"
        ],
        [
          "riso-bianco",
          150,
          "g"
        ],
        [
          "broccoli",
          200,
          "g"
        ]
      ]
    },
    {
      "id": "fav4",
      "name": "Spuntino pomeriggio",
      "items": [
        [
          "mela",
          1,
          "pz"
        ],
        [
          "mandorle",
          25,
          "g"
        ]
      ]
    }
  ],
  "default_goals": {
    "kcal": 2200,
    "p": 130,
    "c": 250,
    "fat": 75,
    "fb": 30,
    "water_ml": 2500
  }
};
